substitutions:
  # Must also define in custom.cpp
  app: bbqmini
  App: BBQ Mini
  location: "mangos"
  Location: "Mangos"
  platform: ESP32
  board: nodemcu-32s
  motorPlatform: ledc
  lcd_cols: "16"
  lcd_rows: "2"
  <<: !include pin_defs.yaml

  # <<: !include pin_defs_d1_mini.yaml

# first time: comment out ip_address and use include wifi_static_ip
<<: !include wifi.yaml
#<<: !include wifi_static_ip.yaml
#<<: !include wwi_mqtt.yaml
#<<: !include nodemcu-32s.yaml
<<: !include core.yaml
<<: !include sensors_1.yaml
