substitutions:
  # Must also define in custom.cpp
  app: bbqmax
  location: "mangos"
  Location: "Mangos"
  platform: ESP32
  board: nodemcu-32s
  motorPlatform: ledc
  lcd_rows: "4"
  <<: !include pin_defs.yaml

  # uncomment if using wifi_static_ip.yaml
  # ip_address: 192.168.2.30

  # <<: !include pin_defs_d1_mini.yaml

# first time: comment out ip_address and use include wifi_static_ip
<<: !include wifi.yaml
#<<: !include wifi_static_ip.yaml
#<<: !include wwi_mqtt.yaml
#<<: !include nodemcu-32s.yaml
<<: !include core.yaml
<<: !include sensors_4.yaml

