sensor:
    # The temperature sensor
  - platform: max6675
    name: "probe_1"
    cs_pin: ${pinProbe1}  # GPIO15  # D8
    update_interval: 15s
    filters:
      - lambda: return dapp.adjust_raw_temp((float)x);
      # - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"    
    on_value:
      lambda: |-
        dapp.process_temp_received(0, (float)x, false);

  # two housekeeping software sensors
  - platform: wifi_signal
    name: "wifi_signal"
    update_interval: 60s

  - platform: uptime
    name: uptime

